### ISSUE TITLE
My Todo list

### ISSUE THREAD

**Issue by cmfcmf** [craigh/ExtensionLibrary#21]
- [x] split release blocks
- [x] add option to auto-create news post on new release
- [x] improve viewreleases page
  - [x] add download links to modals
  - [x] add download links to table
- [x] add jenkins-endpoint to be notified when a jenkins build has finished
